### PR TITLE
fix the pub configuration

### PR DESCRIPTION
**Pull request by ericbaud**

### CODE REVIEW

**Comment by olprod** [comment]
OPS Build status updates of commit _[162aecb](https://github.com/MicrosoftDocs/azure-docs-test2-pr.de-DE/pull/3/commits/162aecb22239745d5202301e553c2ef3f36f3610)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/MicrosoftDocs/azure-docs-test2-pr.de-DE/blob/livepubfix/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C10%5C15e46a3f-2d4e-adae-ff39-b981b129c4dd%5CPullRequest%5C201812102100495837-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mkzoLRuscDSF%2B3WpwUqzKx%2FqqrQg3BeC87pzRmcBAWY%3D&st=2018-12-10T20%3A58%3A21Z&se=2019-01-10T21%3A03%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JasonCard** [comment]
OPS Build status updates of commit _[162aecb](https://github.com/MicrosoftDocs/azure-docs-test2-pr.de-DE/pull/3/commits/162aecb22239745d5202301e553c2ef3f36f3610)_: 

:clock10: **Preparing**: average preparing time is not available, there is no data for this repository.

**Comment by JasonCard** [comment]
OPS Build status updates of commit _[162aecb](https://github.com/MicrosoftDocs/azure-docs-test2-pr.de-DE/pull/3/commits/162aecb22239745d5202301e553c2ef3f36f3610)_: 

:clock10: **Full build**: average full build time is not available, there is no data for this repository.

> Note: A full build is taking more time than an incremental build.  This is the expected behavior of the build system.

**Comment by JasonCard** [comment]
OPS Build status updates of commit _[162aecb](https://github.com/MicrosoftDocs/azure-docs-test2-pr.de-DE/pull/3/commits/162aecb22239745d5202301e553c2ef3f36f3610)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[.openpublishing.publish.config.json](https://github.com/MicrosoftDocs/azure-docs-test2-pr.de-DE/blob/livepubfix/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2018%5C12%5C10%5C15e46a3f-2d4e-adae-ff39-b981b129c4dd%5CPullRequest%5C201812102100490834-3%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rTKkLYqJQilMmaFMubviYa3dhSXmzV0ag7myRjA5lCk%3D&st=2018-12-10T21%3A02%3A45Z&se=2019-01-10T21%3A07%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
